#!/bin/sh
# Copy the compositor's background painter out of the kernel tree into
# bg_extract.inc, so wallgen renders the wallpapers from the same source the OS
# does instead of a drifting copy. Run it before every build; if the kernel side
# changes shape enough that this stops finding its markers, it fails loudly
# rather than emitting a stale file.
set -e

cd "$(dirname "$0")"
SRC=../../kernel/gui/core
OUT=bg_extract.inc

[ -f "$SRC/compositor.c" ] || { echo "extract: $SRC/compositor.c not found" >&2; exit 1; }

{
  echo "// Generated by tools/wallgen/extract.sh — do not edit."
  echo "// Source: kernel/gui/core/{wallpaper_win.h,wallpaper_win.c,compositor.c}"
  echo

  # The style enum + WALLPAPER_COUNT.
  sed -n '/^#define WALLPAPER_COUNT/p' "$SRC/wallpaper_win.h"
  sed -n '/^enum {/,/^};/p'            "$SRC/wallpaper_win.h"
  echo

  # The base-colour palette and the style names (they label the output files).
  sed -n '/^static const struct { uint8_t r, g, b; const char\* name; } palette/,/^};/p' \
      "$SRC/wallpaper_win.c"
  sed -n '/^static const char\* style_names\[/p' "$SRC/wallpaper_win.c"
  echo

  # bg_fill_circle .. draw_background, verbatim. The kernel tree is checked out
  # with CRLF endings on Windows, hence the \r? in the closing-brace match.
  awk '
    /^static void bg_fill_circle\(/  { copy = 1 }
    copy                             { print }
    /^static void draw_background\(/ { inbg = 1; next }
    inbg && /^}\r?$/                 { exit }
  ' "$SRC/compositor.c"
} > "$OUT"

for sym in WALLPAPER_COUNT WP_STYLE_COUNT palette style_names bg_fill_circle wp_isin draw_background; do
  grep -q "$sym" "$OUT" || { echo "extract: '$sym' missing from $OUT — kernel source moved?" >&2; exit 1; }
done

echo "extract: $OUT ($(wc -l < "$OUT") lines)"
