// ============================================================
// aes_cmac.c - AES-CMAC (RFC 4493 / NIST SP 800-38B)
// ============================================================
// A message authentication code built on the AES-128 block cipher rather than a hash.
// Where HMAC keys a hash and Poly1305/SipHash use their own primitives, CMAC is the
// standard block-cipher MAC (OMAC1): it CBC-MACs the message but fixes the classic
// CBC-MAC length-extension weakness by masking the final block with a key-derived
// subkey. Two subkeys are generated by doubling L = E_K(0^128) in GF(2^128):
//
//     K1 = L·x,   K2 = L·x^2   (x = 0x02; reduction polynomial x^128 + x^7 + x^2 + x + 1)
//
// The last message block is XORed with K1 when it is a full 16 bytes, or padded with a
// 0x80 byte (then zeros) and XORed with K2 when it is short (or the message is empty).
// The block cipher itself is the vetted FIPS-197 core exposed from aes_gcm.c — no second
// copy of the S-box or key schedule. Correctness is pinned by the four RFC 4493 §4
// known-answer vectors via aes_cmac_selftest() (the CI `cmac` KAT).
#include "../core/kernel.h"
#include "aes_gcm.h"
#include "aes_cmac.h"

// out = in · x in GF(2^128): a left shift by one bit, and if the top bit was set,
// reduce by XORing 0x87 into the low byte (the constant Rb for the 128-bit field).
static void gf_double(const uint8_t in[16], uint8_t out[16]) {
    uint8_t carry = (uint8_t)(in[0] >> 7);
    for (int i = 0; i < 15; i++)
        out[i] = (uint8_t)((in[i] << 1) | (in[i + 1] >> 7));
    out[15] = (uint8_t)(in[15] << 1);
    if (carry) out[15] ^= 0x87;
}

void aes128_cmac(const uint8_t key[16], const uint8_t* msg, uint32_t len, uint8_t mac[16]) {
    aes128_ctx c;
    aes128_key_expand(&c, key);

    // Subkeys K1, K2 from L = E_K(0).
    uint8_t zero[16], L[16], K1[16], K2[16];
    for (int i = 0; i < 16; i++) zero[i] = 0;
    aes128_encrypt(&c, zero, L);
    gf_double(L, K1);
    gf_double(K1, K2);

    // Block count and whether the last block is a full 16 bytes.
    uint32_t n = (len + 15) / 16;
    int complete;
    if (n == 0) { n = 1; complete = 0; }        // empty message: one padded block
    else        { complete = (len % 16 == 0); }

    // CBC-MAC the first n-1 blocks.
    uint8_t x[16], y[16];
    for (int i = 0; i < 16; i++) x[i] = 0;
    for (uint32_t b = 0; b < n - 1; b++) {
        for (int i = 0; i < 16; i++) y[i] = x[i] ^ msg[b * 16 + i];
        aes128_encrypt(&c, y, x);
    }

    // Final block: whole ⊕ K1, or (msg‖0x80‖0…) ⊕ K2.
    uint8_t last[16];
    uint32_t base = (n - 1) * 16;
    if (complete) {
        for (int i = 0; i < 16; i++) last[i] = msg[base + i] ^ K1[i];
    } else {
        uint32_t rem = len - base;              // 0..15 bytes in the partial block
        for (uint32_t i = 0; i < 16; i++) {
            uint8_t v = (i < rem) ? msg[base + i] : (i == rem ? 0x80 : 0x00);
            last[i] = v ^ K2[i];
        }
    }
    for (int i = 0; i < 16; i++) y[i] = x[i] ^ last[i];
    aes128_encrypt(&c, y, mac);
}

// ---- Known-answer test: RFC 4493 §4 -------------------------------------------------
static int eq16(const uint8_t* a, const uint8_t* b) {
    for (int i = 0; i < 16; i++) if (a[i] != b[i]) return 0;
    return 1;
}
int aes_cmac_selftest(void) {
    // The single RFC 4493 key and the 64-byte example message (NIST SP 800-38A M).
    static const uint8_t key[16] = {
        0x2b,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x3c };
    static const uint8_t msg[64] = {
        0x6b,0xc1,0xbe,0xe2,0x2e,0x40,0x9f,0x96,0xe9,0x3d,0x7e,0x11,0x73,0x93,0x17,0x2a,
        0xae,0x2d,0x8a,0x57,0x1e,0x03,0xac,0x9c,0x9e,0xb7,0x6f,0xac,0x45,0xaf,0x8e,0x51,
        0x30,0xc8,0x1c,0x46,0xa3,0x5c,0xe4,0x11,0xe5,0xfb,0xc1,0x19,0x1a,0x0a,0x52,0xef,
        0xf6,0x9f,0x24,0x45,0xdf,0x4f,0x9b,0x17,0xad,0x2b,0x41,0x7b,0xe6,0x6c,0x37,0x10 };
    struct { uint32_t len; uint8_t mac[16]; } v[] = {
        { 0,  { 0xbb,0x1d,0x69,0x29,0xe9,0x59,0x37,0x28,0x7f,0xa3,0x7d,0x12,0x9b,0x75,0x67,0x46 } },
        { 16, { 0x07,0x0a,0x16,0xb4,0x6b,0x4d,0x41,0x44,0xf7,0x9b,0xdd,0x9d,0xd0,0x4a,0x28,0x7c } },
        { 40, { 0xdf,0xa6,0x67,0x47,0xde,0x9a,0xe6,0x30,0x30,0xca,0x32,0x61,0x14,0x97,0xc8,0x27 } },
        { 64, { 0x51,0xf0,0xbe,0xbf,0x7e,0x3b,0x9d,0x92,0xfc,0x49,0x74,0x17,0x79,0x36,0x3c,0xfe } },
    };
    for (int i = 0; i < 4; i++) {
        uint8_t out[16];
        aes128_cmac(key, msg, v[i].len, out);
        if (!eq16(out, v[i].mac)) return i + 1;
    }
    // Tamper check: one flipped message bit must change the tag.
    uint8_t t1[16], t2[16], bad[16];
    for (int i = 0; i < 16; i++) bad[i] = msg[i];
    aes128_cmac(key, msg, 16, t1);
    bad[3] ^= 0x01;
    aes128_cmac(key, bad, 16, t2);
    if (eq16(t1, t2)) return 5;
    return 0;
}
