#include "libc.h"

/* free — show memory usage. Reads /proc/meminfo (generated by the kernel from its
 * allocator stats) and prints the classic total/used/free table, in kB. */

static char buf[256];

/* Advance *p to the next run of digits and return it as a number, or -1. */
static long next_num(const char** p) {
    while (**p && (**p < '0' || **p > '9')) (*p)++;
    if (!**p) return -1;
    long v = 0;
    while (**p >= '0' && **p <= '9') { v = v * 10 + (**p - '0'); (*p)++; }
    return v;
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;

    long fd = open("/proc/meminfo", O_RDONLY, 0);
    if (fd < 0) { printf("free: cannot read /proc/meminfo\n"); return 1; }
    long n = read((int)fd, buf, sizeof(buf) - 1);
    if (n < 0) n = 0;
    buf[n] = '\0';
    close((int)fd);

    const char* p = buf;
    long total = next_num(&p);   /* MemTotal */
    long used  = next_num(&p);   /* MemUsed  */
    long freeb = next_num(&p);   /* MemFree  */

    /* Right-justified columns (the user printf has no left-justify). */
    printf("        %11s%11s%11s\n", "total", "used", "free");
    printf("Mem: (kB)%11ld%11ld%11ld\n", total, used, freeb);
    return 0;
}
